<?php

/**
 * This file is part of the "laravel-lang/native-locale-names" project.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author Andrey Helldar <helldar@dragon-code.pro>
 * @copyright 2023 Laravel Lang Team
 * @license MIT
 *
 * @see https://laravel-lang.com
 */

declare(strict_types=1);

use LaravelLang\LocaleList\Locale;
use LaravelLang\NativeLocaleNames\Enums\SortBy;
use LaravelLang\NativeLocaleNames\LocaleNames;

it('should not be a clone of the English version')
    ->expect(fn () => LocaleNames::get())
    ->toBeSameCount()
    ->toBe(sourceLocale('_native'))
    ->not->toBe(sourceLocale('en'))
    ->not->toBeEmpty();

it('should check the returned list in French')
    ->expect(fn () => LocaleNames::get(Locale::French, SortBy::Key))
    ->toBe([
        'af'         => 'Afrikaans',
        'ar'         => 'Arabe',
        'az'         => 'Azerbaïdjanais',
        'be'         => 'Biélorusse',
        'bg'         => 'Bulgare',
        'bn'         => 'Bengali',
        'bs'         => 'Bosniaque',
        'ca'         => 'Catalan',
        'cs'         => 'Tchèque',
        'cy'         => 'Gallois',
        'da'         => 'Danois',
        'de'         => 'Allemand',
        'de_CH'      => 'Allemand (Suisse)',
        'el'         => 'Grec',
        'en'         => 'Anglais',
        'es'         => 'Espagnol',
        'et'         => 'Estonien',
        'eu'         => 'Basque',
        'fa'         => 'Persan',
        'fi'         => 'Finnois',
        'fil'        => 'Filipino',
        'fr'         => 'Français',
        'gl'         => 'Galicien',
        'gu'         => 'Goudjarati',
        'he'         => 'Hébreu',
        'hi'         => 'Hindi',
        'hr'         => 'Croate',
        'hu'         => 'Hongrois',
        'hy'         => 'Arménien',
        'id'         => 'Indonésien',
        'is'         => 'Islandais',
        'it'         => 'Italien',
        'ja'         => 'Japonais',
        'ka'         => 'Géorgien',
        'kk'         => 'Kazakh',
        'km'         => 'Khmer',
        'kn'         => 'Kannada',
        'ko'         => 'Coréen',
        'lt'         => 'Lituanien',
        'lv'         => 'Letton',
        'mk'         => 'Macédonien',
        'mn'         => 'Mongol',
        'mr'         => 'Marathi',
        'ms'         => 'Malais',
        'nb'         => 'Norvégien Bokmål',
        'ne'         => 'Népalais',
        'nl'         => 'Néerlandais',
        'nn'         => 'Norvégien Nynorsk',
        'oc'         => 'Occitan',
        'pl'         => 'Polonais',
        'ps'         => 'Pachto',
        'pt'         => 'Portugais',
        'pt_BR'      => 'Portugais (Brésil)',
        'ro'         => 'Roumain',
        'ru'         => 'Russe',
        'sc'         => 'Sarde',
        'si'         => 'Cingalais',
        'sk'         => 'Slovaque',
        'sl'         => 'Slovène',
        'sq'         => 'Albanais',
        'sr_Cyrl'    => 'Serbe',
        'sr_Latn'    => 'Serbe',
        'sr_Latn_ME' => 'Serbe (Monténégro)',
        'sv'         => 'Suédois',
        'sw'         => 'Swahili',
        'tg'         => 'Tadjik',
        'th'         => 'Thaï',
        'tk'         => 'Turkmène',
        'tl'         => 'Tagalog',
        'tr'         => 'Turc',
        'ug'         => 'Ouïghour',
        'uk'         => 'Ukrainien',
        'ur'         => 'Ourdou',
        'uz_Cyrl'    => 'Ouzbek',
        'uz_Latn'    => 'Ouzbek',
        'vi'         => 'Vietnamien',
        'zh_CN'      => 'Chinois (Chine)',
        'zh_HK'      => 'Chinois (R.a.s. Chinoise De Hong Kong)',
        'zh_TW'      => 'Chinois (Taïwan)',
    ]);

it('should check the returned list in Ukrainian')
    ->expect(fn () => LocaleNames::get(Locale::Ukrainian, SortBy::Key))
    ->toBe([
        'af'         => 'Африкаанс',
        'ar'         => 'Арабська',
        'az'         => 'Азербайджанська',
        'be'         => 'Білоруська',
        'bg'         => 'Болгарська',
        'bn'         => 'Бенгальська',
        'bs'         => 'Боснійська',
        'ca'         => 'Каталонська',
        'cs'         => 'Чеська',
        'cy'         => 'Валлійська',
        'da'         => 'Данська',
        'de'         => 'Німецька',
        'de_CH'      => 'Німецька (Швейцарія)',
        'el'         => 'Грецька',
        'en'         => 'Англійська',
        'es'         => 'Іспанська',
        'et'         => 'Естонська',
        'eu'         => 'Баскська',
        'fa'         => 'Перська',
        'fi'         => 'Фінська',
        'fil'        => 'Філіппінська',
        'fr'         => 'Французька',
        'gl'         => 'Галісійська',
        'gu'         => 'Гуджараті',
        'he'         => 'Іврит',
        'hi'         => 'Гінді',
        'hr'         => 'Хорватська',
        'hu'         => 'Угорська',
        'hy'         => 'Вірменська',
        'id'         => 'Індонезійська',
        'is'         => 'Ісландська',
        'it'         => 'Італійська',
        'ja'         => 'Японська',
        'ka'         => 'Грузинська',
        'kk'         => 'Казахська',
        'km'         => 'Кхмерська',
        'kn'         => 'Каннада',
        'ko'         => 'Корейська',
        'lt'         => 'Литовська',
        'lv'         => 'Латиська',
        'mk'         => 'Македонська',
        'mn'         => 'Монгольська',
        'mr'         => 'Маратхі',
        'ms'         => 'Малайська',
        'nb'         => 'Норвезька (Букмол)',
        'ne'         => 'Непальська',
        'nl'         => 'Нідерландська',
        'nn'         => 'Норвезька (Нюношк)',
        'oc'         => 'Окситанська',
        'pl'         => 'Польська',
        'ps'         => 'Пушту',
        'pt'         => 'Португальська',
        'pt_BR'      => 'Португальська (Бразилія)',
        'ro'         => 'Румунська',
        'ru'         => 'Російська',
        'sc'         => 'Сардинська',
        'si'         => 'Сингальська',
        'sk'         => 'Словацька',
        'sl'         => 'Словенська',
        'sq'         => 'Албанська',
        'sr_Cyrl'    => 'Сербська',
        'sr_Latn'    => 'Сербська',
        'sr_Latn_ME' => 'Сербська (Чорногорія)',
        'sv'         => 'Шведська',
        'sw'         => 'Суахілі',
        'tg'         => 'Таджицька',
        'th'         => 'Тайська',
        'tk'         => 'Туркменська',
        'tl'         => 'Тагальська',
        'tr'         => 'Турецька',
        'ug'         => 'Уйгурська',
        'uk'         => 'Українська',
        'ur'         => 'Урду',
        'uz_Cyrl'    => 'Узбецька',
        'uz_Latn'    => 'Узбецька',
        'vi'         => 'Вʼєтнамська',
        'zh_CN'      => 'Китайська (Китай)',
        'zh_HK'      => 'Китайська (Гонконг, Оар Китаю)',
        'zh_TW'      => 'Китайська (Тайвань)',
    ]);
